from typing import Dict, Any
from langchain_core.messages import AIMessage
from graph.state import AgentState
from .llm_utils import get_llm


def consultant_node(state: AgentState) -> Dict[str, Any]:
    """
    The 'Mouth' of the AI Coach.
    Generates expert tactical advice based on the Analyzer's insights.
    This node does NOT modify player positions.
    """
    llm = get_llm()
    
    # Retrieve the rich context generated by the Analyzer
    analysis_context = state.get("analysis", {})
    
    # "snapshot_text" contains the fused data (Location + Skill)
    # e.g., "LeBron James (SF) | Loc: PAINT | Role: Point Forward | Status: Effective Range"
    snapshot_text = analysis_context.get("snapshot_text", "No player data available.")
    tactical_summary = analysis_context.get("tactical_summary", "")
    spacing_score = analysis_context.get("spacing_score", "N/A")
    
    # The user's specific question
    user_question = state['messages'][-1].content
    
    consultant_prompt = f"""
    You are an expert NBA Assistant Coach having a conversation with the Head Coach (the user).
    
    **Current Situation on the Board:**
    - Spacing Grade: {spacing_score}/10
    - Tactical Summary: {tactical_summary}
    
    **Detailed Player Positioning:**
    {snapshot_text}
    
    **User's Question/Comment:**
    "{user_question}"
    
    **Instructions:**
    1. Answer the user's question directly and professionally.
    2. Use the data to back up your claims. 
       - Example: Instead of saying "The center is out of position", say "Anthony Davis is clogging the spacing at the 3-point line."
    3. Keep it conversational but concise (max 2-3 sentences unless asked for a detailed breakdown).
    4. If the user suggests a bad idea, explain *why* based on the player's skills (e.g., "That might not work because Gobert can't shoot threes").
    
    Provide your expert advice now.
    """
    
    # Generate the response
    response = llm.invoke([{"role": "user", "content": consultant_prompt}])
    
    # Return the message to be displayed in the chat
    return {
        "messages": [AIMessage(content=response.content)]
    }
